# Generated by Django 4.2.1 on 2023-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_Type', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Unit Type')),
                ('unit_ID', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Unit ID')),
            ],
        ),
    ]
