# Generated by Django 4.2.1 on 2023-05-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenanceform_pic_officer'),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crews',
            new_name='Crew',
        ),
    ]
