# Generated by Django 4.2.1 on 2023-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Title')),
                ('doc_no', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Doc. No.')),
                ('issue_date', models.DateField(blank=True, default=None, null=True, verbose_name='Issue Date')),
                ('revision_no', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Revision No.')),
            ],
        ),
    ]
