# Generated by Django 4.2.1 on 2023-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenanceform_pm_no_maintenanceform_wo_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceform',
            name='time_Finish',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Time Finish'),
        ),
        migrations.AddField(
            model_name='maintenanceform',
            name='time_Start',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Time Start'),
        ),
    ]
