# Generated by Django 4.2.1 on 2023-05-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        ('maintenance', '0004_maintenanceform_time_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceform',
            name='pic_Officer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.crews'),
        ),
    ]
