# Generated by Django 4.2.1 on 2023-05-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('crew', '0002_rename_crews_crew'),
        ('maintenance', '0006_rename_maintenanceform_preventivemaintenancewo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreventiveMaintenanceWO',
            new_name='PreventiveWO',
        ),
    ]
